services:
  - type: web
    name: fastapi-image-gen
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GETIMG_API_KEY
        sync: false
      - key: MONGO_URI
        sync: false